- docs/deployment.md
- pkg/controller/helmrelease/helmrelease_controller.go
- pkg/helmreleasemgr/helmreleasemgr.go
- pkg/helmreleasemgr/helmreleasemgr_test.go
- https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/740 (Panic if releaseName less than 4 chars)
- Reduce the max retry period from 6h to 2 min for helmrelease
- Update doc for keywords vs labelSelector
> Dvernier release name too short 740

- OWNERS
- pkg/controller/helmrelease/helmrelease_controller.go
- pkg/controller/helmrelease/helmrelease_controller_suite_test.go
- pkg/controller/helmrelease/helmrelease_controller_test.go
- pkg/controller/helmrelease/helmreleasemgr.go
Signed-off-by: Kuan Feng <fengkuan@gmail.com>
- added team member
- use single controller-runtime/manager rather than 1 for each release
- use controllerutil.SetOwnerrefernce to ensure controller:true is set
- consolidate the Update action
- Change the test from recFn with channel to simply Add
> add team members to owner list and several other updates/fixes

- OWNERS
- deploy/crds/app_v1alpha1_helmchartsubscription_cr.yaml
- pkg/utils/helmrepoutils.go
- pkg/utils/helmrepoutils_test.go
- fixed `channel` cannot be empty for the deploy cr
- fixed downloadFile() not checking if it's able to parse the file name correctly
- fixed downloadFileHTTP() not checking if it's a file or directory. It was skipping download because the directory exists.
- fixed DownloadChartFromHelmRepo() never returning any error because it uses `:=` to assign and then `continue` which wipes the error value.
> fix helm repo utils download chart from helm repo not handling errors properly

- deploy/operator.yaml
Image is set to multicloudlab/multicloud-operators-subscription-release
Signed-off-by: Richard Su <rwsu@redhat.com>
> Fix image reference by pointing to quay.io

- deploy/crds/app.ibm.com_helmreleases_crd.yaml
- docs/deployment.md
- pkg/apis/app/v1alpha1/helmrelease_types.go
- pkg/apis/app/v1alpha1/zz_generated.openapi.go
- pkg/controller/helmrelease/helmrelease_controller.go
- pkg/controller/helmrelease/helmrelease_controller_test.go
- pkg/controller/helmrelease/helmreleasemgr.go
- pkg/helmreposubscriber/hrsubscriber.go
- pkg/helmreposubscriber/hrsubscriber_test.go
- pkg/utils/helmrepoutils.go
- pkg/utils/helmrepoutils_test.go
- Consolidate releasename and cr name into just using cr name
- Remove The spec.releasename, remove the creation of secret
- Use the actual helmrelease cr for helm manager
complimentary commit on the subscription side: https://github.com/mikeshng/multicloud-operators-subscription/commit/6c0b8029920c941641302a8620c6b960ca9ee029 (need `-release` to merge in first so I can change the go.mod to reference the dependency)
Signed-off-by: Mike Ng <mikeshngdev@gmail.com>
> consolidate releasename and cr name into just using cr name

- go.mod
- go.sum
We are currently referencing a commit because we needed the helm version update fix. Now operator-sdk has a proper release that we can reference.
> move operator-sdk version to v0.16.0

- pkg/controller/helmrelease/helmrelease_controller_test.go
- pkg/controller/helmrelease/helmreleasemgr.go
> return resource list instead of string for helm manifest generation

- pkg/controller/helmrelease/helmrelease_controller.go
- pkg/controller/helmrelease/helmrelease_controller_test.go
> add the ability to force a helm update even if the old and new manifests are the same

- go.mod
- pkg/controller/helmrelease/helmrelease_controller.go
- fix skip upgrade logic
- prevent force upgrade hanging by adding timeout
- remove redundant logic to check helm operator reconcile return
- fix potential panic crash from closing channel
https://github.com/open-cluster-management/backlog/issues/3300
> Rework reconcile logic

- pkg/controller/helmrelease/helm_operator.go
- pkg/controller/helmrelease/helm_operator_test.go
- pkg/controller/helmrelease/helmrelease_controller.go
- pkg/controller/helmrelease/helmrelease_controller_test.go
- pkg/controller/helmrelease/helmreleasemgr.go
https://github.com/open-cluster-management/backlog/issues/3668
- Also removed `GenerateResourceListByConfig()` it's no longer being used.
- Moved `forceUpgradeRelease()` from controller to its helm_operator.go
> cleanup all the resources before removing the finalizer

- deploy/operator.yaml
- deploy/role.yaml
- deploy/role_binding.yaml
- deploy/service_account.yaml
The fix is mostly in
`image: quay.io/open-cluster-management/multicluster-operators-subscription-release:community-latest`
> fixed image path

- deploy/crds/apps.open-cluster-management.io_helmreleases_crd.yaml
- pkg/apis/apps/v1/helmrelease_types.go
- pkg/apis/apps/v1/zz_generated.openapi.go
- pkg/utils/helmrepoutils.go
https://github.com/open-cluster-management/backlog/issues/6857
HelmRelease CRD only supports repo.configMapRef to specify insecureSkipVerify=true. We need to add insecureSkipVerify to the spec as well just to specify it without the config map. Also update the controller to look for this to skip verifying Helm server cert.
> Spec change to support insecureSkipVerify

- pkg/release/manager.go
discovered while working on `https://github.com/operator-framework/operator-sdk/pull/3431` for the operator-sdk guys.
> fix helm uninstall possible nil pointer

- cmd/manager/exec/manager.go
Hi @xiangjingli 
I don't know how we got the initial port numbers but this is what I plan to use for all 6 of our repos. Please let me know if you have any concerns. Thanks.
```
subscription
metricsPort         int32 = 8381
operatorMetricsPort int32 = 8684
subscription-release
metricsPort         int = 8382
operatorMetricsPort int = 8685
placementrule
metricsPort         int = 8383
operatorMetricsPort int = 8686
channel
metricsPort         int32 = 8384
operatorMetricsPort int32 = 8687
deployable
metricsPort         int32 = 8385
operatorMetricsPort int32 = 8688
application
metricsPort         int = 8386
operatorMetricsPort int = 8689
```
> update metric ports

- pkg/controller/helmrelease/helmrelease_helper.go
https://github.com/open-cluster-management/backlog/issues/8108
if `Status.DeployedRelease` is nil then there is no need to try to strip CRDs from the manifest because there is no manifest to strip.
> fixed a nilpointer when trying to remove CRD from the helmreleast deployrelease manifest

- pkg/controller/helmrelease/helmrelease_controller.go
- pkg/controller/helmrelease/helmrelease_helper.go
- pkg/release/manager.go
Use Helm's internal functions to parse the manifest so that we detect the ACM CRDs that we want to remove in a more reliable manner. The previous version just treats the manifest as a yaml string with some regex which is probably not as reliable as Helm's functions when it comes to parsing.
> use helm functions to parse the manifest

- go.mod
- go.sum
- pkg/controller/helmrelease/helmrelease_controller.go
- pkg/controller/helmrelease/helmrelease_helper.go
- pkg/release/manager.go
- pkg/release/manager_test.go
for https://github.com/open-cluster-management/backlog/issues/8261
- added strip crds if the helmrelease came from ACM
- skip uninstall rollback if the deployedrelease already exists
- call manager sync after Helm delete logic
these PRs are pulled over
https://github.com/open-cluster-management/multicloud-operators-subscription-release/pull/130
https://github.com/open-cluster-management/multicloud-operators-subscription-release/pull/131
https://github.com/open-cluster-management/multicloud-operators-subscription-release/pull/133
https://github.com/open-cluster-management/multicloud-operators-subscription-release/pull/134
https://github.com/open-cluster-management/multicloud-operators-subscription-release/pull/135
I think besides some dependencies differences and the `InsecureSkipVerify` …
> pull changes from release-2.1 to master

- go.mod
- go.sum
Signed-off-by: Xiangjing Li <xiangli@redhat.com>
https://github.com/open-cluster-management/backlog/issues/8154
> upgrade golang.org/x/crypto to latest to resolve its CVE

- README.md
- pkg/apis/apps/v1/helmrelease_types.go
- pkg/apis/apps/v1/zz_generated.openapi.go
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/controller/helmrelease/helmrelease_controller.go
- pkg/controller/helmrelease/helmrelease_controller_test.go
- pkg/controller/helmrelease/helmreleasemgr.go
- pkg/release/manager.go
- pkg/release/manager_factory.go
- HelmRelease delete shouldn't need to download charts to work.
- pull operator-sdk upstream fixes
- added `digest` (to be populated by the appsub side similar to version)
part 1 of https://github.com/open-cluster-management/backlog/issues/8603
> various enhancements to helmrelease

- test/github/nginx-chart/Chart.yaml
- test/github/nginx-chart/templates/NOTES.txt
- test/github/nginx-chart/templates/_helpers.tpl
- test/github/nginx-chart/templates/deployment.yaml
- test/github/nginx-chart/templates/service.yaml
- test/github/nginx-chart/values.yaml
1. This patch is to solve https://github.com/open-cluster-management/multicloud-operators-subscription-release/pull/167/files#r593255104
2. Add chart to this github repo itself, the helm repo will refer to this link.
> Add nginx-chart for HelmRelease test

- examples/test-guestbook-spec-change.yaml
1. Add the YAML file with HelmRelease specifying spec field
2. This YAML file will be used for testing " A spec change update". It's related with https://github.com/open-cluster-management/multicloud-operators-subscription-release/pull/165. It changed the spec fields:   "replicaCount: 4" ->  "replicaCount: 3:
> HelmRelease with spec change YAML

- examples/test-guestbook-spec-unused.yaml
1. Add the YAML file with HelmRelease specifying spec field which not used by chart
2. This YAML file will be used for testing " Spec with fields that are not used in the chart."  In this YAML file, we define "unused: unused" in the spec filed.
> HelmRelease with spec fields unused by chart

- test/github/nginx-chart/templates/deployment.yaml
1. This label will be used to check if the HelmRelease Spec fields is applied correctly.
> Add replicas label to chart

- examples/test-guestbook-spec-change.yaml
This YAML file is mainly focus on spec change testing. And the change will be compared with previous YAML deployment.  It's necessary to distinguish a fully deployment and a changed deployment.
So we should remove unchanged but necessary part, and only keep the HelmRelease part in which the spec fields changes. Then we check if the  deployment is successful with the changes.
> Remove namespace from yaml file for spec change testing

- examples/test-guestbook-helmrepo-spec-change.yaml
- examples/test-guestbook-helmrepo-spec-unused.yaml
- examples/test-guestbook-helmrepo-spec.yaml
- examples/test-guestbook-helmrepo-upgrade.yaml
- examples/test-guestbook-helmrepo.yaml
1. test-guestbook-helmrepo.yaml will be used  for helmrepo type chart deployment for basic
2. test-guestbook-helmrepo-upgrade.yaml will be used for helmrepo type chart deployment upgrade testing
3. test-guestbook-helmrepo-spec.yaml will be used for helmrepo type chart with spec fields testing
4. test-guestbook-helmrepo-spec-change.yaml will be used for helmrepo type chart with spec fields change testing
5. test-guestbook-helmrepo-spec-unused.yaml will be used for helmrepo type chart with unused spec fields testing
> Add yaml files for helmrepo testings

- apache-basic-auth/apache-basic-auth-service.yaml
- build/run-e2e-tests.sh
- e2e/e2e_test.go
1. Add all test IDs to e2e
2. Extend the go time time from 10 minutes to 30 minutes
3. Update version with applifecycle-backend-e2e@v0.2.3
4. For case RHACM4K-1680, we need to deploy a pod with basic auth and chart. apache-basic-auth-service.yaml aims to solve this.
> Add all 11 test IDs

- pkg/controller/helmrelease/helmrelease_controller.go
note: We are getting close to release so I don't want to make too much code changes such as setting the error status. I will add that for the beginning of next release.
> avoid a nil pointer when Repo.Source is not defined

- go.mod
- go.sum
https://github.com/open-cluster-management/backlog/issues/16343
needs to update subscription repo after this is merge
> fix go mod to remove sec vuln depend

- pkg/controller/helmrelease/helmrelease_controller.go
- pkg/controller/helmrelease/helmreleasemgr.go
Back porting changes from https://github.com/stolostron/multicloud-operators-subscription/pull/655 to release-2.4 branch
After this is merged, we still need to update the subscription side to use the new HR version and `metaupdate.go`
For https://github.com/stolostron/backlog/issues/19823
> set default value for helmrelease chart directory
