stolostron/multicloud-operators-subscription-release

Makefile
build/install-operator-sdk.sh

install operator-sdk

---

.github/dco.yml
Makefile
README.md
build/install-operator-sdk.sh
docs/deployment.md
docs/development.md
go.mod

Update Readme/docs and move to go 1.13

Update Readme/docs and move to Go 1.13

---

cmd/manager/main.go
go.mod
go.sum
pkg/controller/helmchartsubscription/helmchartsubscription_controller.go
pkg/controller/helmrelease/helmrelease_controller.go
pkg/helmreleasemgr/helmreleasemgr.go
pkg/helmreleasemgr/helmreleasemgr_suite_test.go
pkg/helmreleasemgr/helmreleasemgr_test.go
pkg/helmreposubscriber/hrsubscriber.go
pkg/helmreposubscriber/hrsubscriber_suite_test.go
pkg/helmreposubscriber/hrsubscriber_test.go
pkg/utils/helmrepoutils.go
pkg/utils/helmrepoutils_suite_test.go
pkg/utils/helmrepoutils_test.go

Move to klog

---

deploy/crds/app_v1alpha1_helmchartsubscription_crd.yaml
pkg/apis/app/v1alpha1/helmchartsubscription_types.go
pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
pkg/helmreposubscriber/hrsubscriber.go
pkg/helmreposubscriber/hrsubscriber_test.go
pkg/utils/helmrepoutils.go
pkg/utils/helmrepoutils_test.go
pkg/utils/kubernetes.go
pkg/utils/kubernetes_test.go

https://github.ibm.com/IBMPrivateCloud/CP4MCM/issues/733

Implement labelSelector

---

pkg/controller/helmchartsubscription/helmchartsubscription_controller.go
pkg/controller/helmrelease/helmrelease_controller.go
pkg/helmreleasemgr/helmreleasemgr_test.go

Reduce nb reconcile, add uni-tests

---

cmd/manager/main.go

Klog.InitFlags misplaced

---

Makefile
common/scripts/.githooks/pre-commit
pkg/helmreposubscriber/hrsubscriber.go
pkg/utils/helmrepoutils.go
pkg/utils/kubernetes.go
pkg/utils/kubernetes_test.go

Only GitHub must have accessToken, helmRepo remains with password

Dvernier password access token

---

pkg/controller/helmrelease/helmrelease_controller.go
pkg/utils/helmrelease.go
pkg/utils/helmrelease_test.go

Add finalizer and manage delete

---

docs/deployment.md
pkg/controller/helmrelease/helmrelease_controller.go
pkg/controller/helmrelease/helmrelease_controller_test.go
pkg/helmreposubscriber/hrsubscriber.go
pkg/helmreposubscriber/hrsubscriber_test.go
pkg/utils/helmrepoutils.go
pkg/utils/helmrepoutils_test.go
pkg/utils/kubernetes.go

Code cleaning and refactoring

---

pkg/controller/helmrelease/helmrelease_controller.go
pkg/utils/helmrelease.go

Check if helmrelease installed before uninstall

---

pkg/controller/helmrelease/helmrelease_controller_suite_test.go
pkg/helmreleasemgr/helmreleasemgr.go
pkg/helmreleasemgr/helmreleasemgr_test.go
pkg/utils/helmrepoutils.go
pkg/utils/helmrepoutils_test.go

Create fake chart.yaml on del if download failed

---

deploy/crds/app.ibm.com_helmchartsubscriptions_crd.yaml
deploy/crds/app.ibm.com_helmreleases_crd.yaml
pkg/apis/app/v1alpha1/helmchartsubscription_types.go
pkg/apis/app/v1alpha1/helmrelease_types.go
pkg/controller/helmrelease/helmrelease_controller_test.go

Add logs to find out why test fails on prow

---

OWNERS

Signed-off-by: Mike Ng <mikeshngdev@gmail.com>

update owners of the repo

---

OWNERS
pkg/apis/app/v1alpha1/zz_generated.deepcopy.go

Signed-off-by: Mike Ng <mikeshngdev@gmail.com>

use yaml marshal for deep copy spec

---

deploy/operator.yaml
test/github/subscription-release-test-1/values.yaml
test/github/subscription-release-test-2/values.yaml

use the new url for image location

---

test/github/subscription-release-test-3/.helmignore
test/github/subscription-release-test-3/Chart.yaml
test/github/subscription-release-test-3/templates/_helpers.tpl
test/github/subscription-release-test-3/templates/deployment_subscription_release.yaml
test/github/subscription-release-test-3/values.yaml

new tests Deployments are now in apps/v1 API version

---

README.md

fixed badges

---

go.mod
go.sum

move operator-sdk version to v0.16.0 (#58)

---

build/Dockerfile

use ubi 8.1 for image

---

pkg/apis/apps/v1/helmrelease_types.go
pkg/controller/helmrelease/helmrelease_controller.go

For https://github.com/open-cluster-management/backlog/issues/1054

Changed MaxConcurrentReconciles from 1 to 10. Added timedout logic

---

.travis.yml
Makefile

Signed-off-by: ianzhang366 <ian.w.zhang@redhat.com>
https://github.com/open-cluster-management/backlog/issues/1060
Fixing above

release repo tagging image for community operator

---

README.md

added coverage badge

---

cmd/manager/main.go
pkg/controller/helmrelease/helmrelease_controller.go

add flag to expose MaxConcurrentReconciles configuration

---

pkg/controller/helmrelease/helmrelease_controller.go

add env variable for max concurrent reconcile

---

deploy/crds/apps.open-cluster-management.io_helmreleases_crd.yaml

make crd compatible with kube 1.1, 1.3

---

.travis.yml

add security scan

---

pkg/controller/helmrelease/helmrelease_controller.go

For https://github.com/open-cluster-management/backlog/issues/993

for reverting spec back to default

---

pkg/utils/helmrepoutils.go
pkg/utils/helmrepoutils_test.go

remediate security scan

---

docs/deployment.md
test/github/subscription-release-test-1/Chart.yaml
test/github/subscription-release-test-1/templates/deployment_subscription_release.yaml
test/github/subscription-release-test-1/values.yaml
test/github/subscription-release-test-2/Chart.yaml
test/github/subscription-release-test-2/templates/deployment_subscription_release.yaml
test/github/subscription-release-test-2/values.yaml
test/github/subscription-release-test-3/Chart.yaml
test/github/subscription-release-test-3/templates/deployment_subscription_release.yaml
test/github/subscription-release-test-3/values.yaml

added red hat copy right

---

pkg/apis/apps/v1/helmrelease_types.go
pkg/controller/helmrelease/helmrelease_controller.go
pkg/controller/helmrelease/helmrelease_controller_test.go
pkg/controller/helmrelease/helmreleasemgr.go

skip update reconcile if update is not required

---

pkg/controller/helmrelease/helmrelease_controller_test.go
sonar-project.properties

refractor some tests

---

pkg/controller/helmrelease/helmrelease_controller.go
pkg/controller/helmrelease/helmrelease_controller_test.go
pkg/controller/helmrelease/helmreleasemgr.go

add a function to generate the manifest given a HelmRelease

Generate Helm manifest

---

pkg/controller/helmrelease/helmrelease_controller_test.go

unit test fix

---

pkg/controller/helmrelease/helm_operator.go

https://github.com/open-cluster-management/backlog/issues/4009

remove unreliable namespace scope check

---

pkg/controller/helmrelease/helm_operator.go

only perform cleanup deployedrelease if it exists

---

pkg/controller/helmrelease/helm_operator_test.go
pkg/controller/helmrelease/helmrelease_controller.go
pkg/controller/helmrelease/helmrelease_controller_test.go
pkg/controller/helmrelease/helmreleasemgr.go

For https://github.com/open-cluster-management/backlog/issues/4546

fix install and upgrade status sometimes its not set properly

---

pkg/utils/helmrepoutils.go

Addressing issue:
https://github.com/open-cluster-management/backlog/issues/5001
Signed-off-by: Ian Zhang <izhang@redhat.com>

fix the issue 5001

---

README.md
docs/deployment.md
docs/development.md

update community doc

---

.gitignore
.travis.yml
Makefile
build/run-e2e-tests.sh
deploy/operator.yaml
e2e/e2e_test.go
examples/test-guestbook010.yaml

Signed-off-by: Ian Zhang <izhang@redhat.com>

working e2e

---

Makefile

fix make target build-images

---

Makefile
build/run-e2e-tests.sh
build/set_up_e2e_local_dir.sh

Signed-off-by: Ian Zhang <izhang@redhat.com>

e2e helper make targets

---

.gitignore
build/run-e2e-tests.sh

Download kubectl binary on macOS
reference pr - https://github.com/open-cluster-management/multicloud-operators-subscription-release/pull/119

Download kubectl on macOS

---

pkg/controller/helmrelease/helm_operator.go
pkg/controller/helmrelease/helmrelease_controller.go
pkg/controller/helmrelease/helmrelease_controller_test.go

For https://github.com/open-cluster-management/backlog/issues/7652 
This is for the release-2.1 branch aim to be include for 2.1.2

release-2.1 - skip delete resource in cleanup steps for resources with the keep Helm resource-policy

---

pkg/controller/helmrelease/helmrelease_helper.go

best effort to find if it's an ACM HelmRelease

---

examples/test-guestbook-git.yaml

This patch add the YAML file which setup helm chart with git repo.

Add helm chart with git repo

---

examples/test-guestbook-secret.yaml

1. Add secret
2. Using local server with basic auth

Add helm chart YAML file for helmrepo with secret

---

examples/test-guestbook-secret.yaml

1. Resolve the pod cannot get access to external host issue

Expose service of apache-basic-auth pod

---

pkg/controller/helmrelease/helmrelease_helper.go

for https://github.com/open-cluster-management/backlog/issues/8388

release-2.1 only: fix logging in helmrelease helper

---

examples/test-guestbook-git-upgrade.yaml

1. Update the chart info which need to be upgraded
2. Upgrade the version info from  0.1.0 to 0.2.0.

Add helm chart upgrade YAML file for helmrepo with git

---

Makefile.prow
build/Dockerfile.prow

added makefile and dockerfile for prow only

---

.gitignore

Testing this remove in this repo first before doing it to the other 5 repos

remove build-harness

---

build/Dockerfile.prow

please still review. merging for now.

docker file prow changes

---

build/Dockerfile.prow

merging for now, please review still.

fix docker prow

---

Makefile.prow

skip e2e in unit tests

---

examples/test-guestbook-spec.yaml

1. Add the YAML file with HelmRelease specifying spec field
2. This YAML file will be used for testing " A normal sunny deployment with some spec defined"

HelmRelease with spec YAML 

---

Makefile.prow
build/run-code-lint.sh
common/scripts/lint_go.sh

fix prow lint

---

examples/test-guestbook-git-upgrade.yaml
examples/test-guestbook-git.yaml
test/github/nginx-chart-upgrade/nginx-chart/Chart.yaml
test/github/nginx-chart-upgrade/nginx-chart/templates/NOTES.txt
test/github/nginx-chart-upgrade/nginx-chart/templates/_helpers.tpl
test/github/nginx-chart-upgrade/nginx-chart/templates/deployment.yaml
test/github/nginx-chart-upgrade/nginx-chart/templates/service.yaml
test/github/nginx-chart-upgrade/nginx-chart/values.yaml

1. Replace my personal github link with this repo itself
2. Add a new directory  nginx-chart-upgrade for previous chart upgrade testing

Relace private github with public github

---

README.md

test prow image publishing

---

README.md

test prow publish image

---

Makefile
deploy/operator.yaml

use latest instead of community-latest

---

.github/workflows/kind.yml
Makefile.prow
build/run-e2e-tests.sh

add github action kind test

---

.github/workflows/kind.yml
build/run-e2e-tests.sh

Signed-off-by: Pei Zhang <pezhang@redhat.com>

Fetch latest version tag of applifecycle-backend-e2e git repo

---

README.md
build/generate-helmrepo.sh
pkg/controller/helmrelease/helmrelease_controller_test.go
pkg/utils/helmrepoutils_test.go

https://github.com/open-cluster-management/backlog/issues/11559
Signed-off-by: Philip Wu <phwu@redhat.com>

Generate new image to fix CVE

---

deploy/crds/apps.open-cluster-management.io_helmreleases_crd_v1.yaml
deploy/crds/v1beta1/apps.open-cluster-management.io_helmreleases_crd_v1beta1.yaml
pkg/utils/helmrepoutils.go

fix a bad error message when the type is git

---

pkg/controller/helmrelease/helmreleasemgr.go
pkg/release/manager_factory.go

Signed-off-by: Mike Ng <ming@redhat.com
quick and safe improvement for https://github.com/open-cluster-management/backlog/issues/10498

improve error message to let user know how to fix the issue

---

pkg/utils/helmrepoutils.go
pkg/utils/helmrepoutils_test.go

for https://github.com/open-cluster-management/backlog/issues/11315
after this is merged, I will make the PR for subscription repo to use the new sub-release version.

add digest to filename

---

pkg/controller/helmrelease/helmrelease_controller.go
pkg/controller/helmrelease/helmrelease_helper.go

I need to use this function on the subscription repo side for https://github.com/open-cluster-management/backlog/issues/13099

expose the GetCapabilities function as a library function

---

.github/workflows/kind.yml
build/Dockerfile.prow
go.mod

Signed-off-by: Xiangjing Li <xiangli@redhat.com>
https://github.com/open-cluster-management/backlog/issues/15570

upgrade to golang 1.17

---

.github/workflows/kind.yml
build/Dockerfile.prow
build/setup-tests.sh
go.mod

Signed-off-by: Xiangjing Li <xiangli@redhat.com>
https://github.com/open-cluster-management/backlog/issues/15572

upgrade to go 1.17

---

build/run-e2e-tests.sh
pkg/utils/helmrepoutils_test.go
pkg/utils/kubernetes.go

Fix the namespace handling of channel secrets and configmaps.
https://github.com/stolostron/backlog/issues/20358

Fix secret namespace

---

README.md

Signed-off-by: Xiangjing Li <xiangli@redhat.com>

trigger image build

---

README.md

toggle cicd build
